#------------------------------------------------------------------------------ 
# Ansible playbook to deploy F5 ARM template for ha-avset, existing stack, BYOL
# 
# Stephen Archer, F5, 20-12-2017.
#------------------------------------------------------------------------------ 
#
# Install pre-requisites before running ansible playbook (for F5 and Azure):
#
# install python-pip:
#   sudo yum -y install epel-release
#   sudo yum -y update
#   sudo yum -y install python-pip python-setuptools python-netaddr python-devel
# install the requirements:
#   sudo pip install -U pip setuptools
#   sudo pip install f5-sdk bigsuds
#   sudo pip install packaging
#   sudo pip install ansible[azure]
#
# No need to specify inventory file.  Just run:
#   ansible-playbook azure-arm-deployment.yaml
#
# Azure paramaters required:
#   tenant-id:              # this is your Directory ID (go to Azure Active Directory > Properties. The Directory ID is your Tenant ID)
#   client-id:              # this is your Application ID (you need to create an Azure AD 'Application' for the BIG-IP to use)
#   servicePrincipalSecret: # this is your application key value (create a key within your AD 'Application')
#
# Requires an existing network stack.  VNet should include the following three subnets (or similar):
#   mgmt       - 10.1.0.0/24
#   external   - 10.1.1.0/24
#   internal   - 10.1.2.0/24
#
# For addition pre-requisites, check https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/ha-avset/existing_stack#prerequisites
#
#------------------------------------------------------------------------------ 


- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Create Azure Deploy
      azure_rm_deployment:
        state: present
        subscription_id: <REPLACE WITH YOUR SUBS ID>
        resource_group_name: bigip-havset
        template_link: "https://raw.githubusercontent.com/F5Networks/f5-azure-arm-templates/master/supported/ha-avset/existing_stack/BYOL/azuredeploy.json"
        location: ukwest
        client_id: <REPLACE WITH YOUR CLIENT ID>
        tenant: <REPLACE WITH YOUR TENNANT ID>
        secret: <REPLACE WITH YOUR SECRET>
        parameters:
          adminUsername:
            value: <DESIRED F5 USERNAME>
          adminPassword:
            value : <COMPLEX F5 PASSWORD>
          dnsLabel:
            value: my-dns 
          instanceName:
            value: bigip
          instanceType:
            value: Standard_DS3_v2
          bigIpVersion:
            value: latest
          imageName:
            value: Best
          licenseKey1:
            value: <VALID F5 LICENSE KEY>
          licenseKey2:
            value: <VALID F5 LICENSE KEY>
          numberOfExternalIps:
            value: 1
          vnetName:
            value: <YOUR VNET NAME>
          vnetResourceGroupName:
            value: <YOUR RG NAME>
          mgmtSubnetName:
            value: mgmt
          mgmtIpAddressRangeStart:
            value: 10.1.1.10
          externalSubnetName:
            value: external
          externalIpSelfAddressRangeStart:
            value: 10.1.2.10
          externalIpAddressRangeStart:
            value: 10.1.2.100
          internalSubnetName:
            value: internal
          internalIpAddressRangeStart:
            value: 10.1.3.10
          tenantId:
            value: <REPLACE WITH YOUR TENNANT ID>
          clientId:
            value: f<REPLACE WITH YOUR CLIENT ID>
          servicePrincipalSecret:
            value: <REPLACE WITH YOUR SERVICE PRINCIPAL SECRET>
          managedRoutes:
            value: 0.0.0.0/0,10.1.4.0/24,10.1.5.0/24,10.1.99.0/24
          routeTableTag:
            value: myRoute
          ntpServer:
            value: 0.pool.ntp.org
          timeZone:
            value: UTC
          restrictedSrcAddress:
            value: "*"
          tagValues:
            value:
              application: APP
              cost: COST
              environment: ENV
              group: GROUP
              owner: OWNER
          allowUsageAnalytics:
            value: 'Yes'