#------------------------------------------------------------------------------ 
# Ansible playbook to deploy F5 CFT template for stand-alone, existing stack, BYOL
# 
# Stephen Archer, F5, 20-12-2017.
#------------------------------------------------------------------------------ 
#
# Install pre-requisites before running ansible playbook (for F5 and AWS):
#
# install python-pip:
#   sudo yum -y install epel-release
#   sudo yum -y update
#   sudo yum -y install python-pip python-setuptools python-netaddr python-devel
# install the requirements:
#   sudo pip install -U pip setuptools
#   sudo pip install f5-sdk bigsuds
#   sudo pip install packaging
#   sudo pip install ansible[aws]
#
# No need to specify inventory file.  Just run:
#   ansible-playbook your_playbook.yaml
#
# AWS paramaters required:
#   ec2_access_key:         # this is your AWS EC2 Access Key
#   ec2_secret_key:         # this is your AWS EC2 Access Key
#   servicePrincipalSecret: # this is your application key value (create a key within your AD 'Application')
#
# Requires an existing network stack.  VNet should include the following three subnets:
#   Management - 10.0.0.0/24
#   External   - 10.0.1.0/24
#   Internal   - 10.0.2.0/24
#
# For addition pre-requisites, check https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/ha-avset/existing_stack#prerequisites
#
#------------------------------------------------------------------------------ 
- name: Provision ec2 instances based on the environment
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: launch ansible cloudformation example
    cloudformation:
      stack_name: "ansible-cloudformation-f5-existing-stack-byol-2nic-bigip"
      state: "present"
      ec2_access_key: "xxxxxxxx"
      ec2_secret_key: "xxxxxxxx"
      region: "eu-west-2"
      disable_rollback: true
      template_url: "https://s3.amazonaws.com/f5-cft/f5-existing-stack-byol-2nic-bigip.template"
      template_parameters:
        imageName: "AllOneBootLocation"
        instanceType: "m4.xlarge"
        licenseKey1: "ENBGS-SBHQD-KUYIB-XCHEH-BMQSLBN"
        Vpc: "vpc-0dfffb8f73f13449e"
        managementSubnetAz1: "subnet-0cc97d670b8fc6ef1"
        subnet1Az1: "subnet-098af3cbf86f9f8c8"
        restrictedSrcAddress: "0.0.0.0/0"
        restrictedSrcAddressApp: "0.0.0.0/0"
        sshKey: "arch_public_2"
        ntpServer: "0.pool.ntp.org"
        timezone: "UTC"
      tags:
        Stack: "ansible-cloudformation-f5-existing-stack-byol-2nic-bigip"
